- name: Update packages
  apt:
    update_cache: yes
    cache_valid_time: 3600
    upgrade: safe

- name: Install packages
  apt:
    name: nfs-kernel-server
    state: present

- name: Edit host file
  blockinfile:
    path: /etc/hosts
    block: |
      192.168.100.100 k8s-master.localhost.com k8s-master
      192.168.100.101 k8s-node-1.localhost.com k8s-node-1
      192.168.100.102 k8s-node-2.localhost.com k8s-node-2
      192.168.100.150 k8s-nfs.localhost.com    k8s-nfs

- name: Enable service
  systemd:
    name: nfs-server
    state: started
    enabled: yes

- name: Setup mount
  file:
    state: directory
    path: /var/nfs/kubernetes
    mode: 0755

- name: Configure nfs export
  blockinfile:
    path: /etc/exports
    state: present
    block: |
      /var/nfs/kubernetes    192.168.100.0/24(rw,sync,no_subtree_check,insecure)

- name: Export directory
  command: exportfs -a

- name: Restart the service
  systemd:
    name: nfs-kernel-server
    state: restarted
